ALTER TABLE `dotnet`.`parts` 
ADD COLUMN `PartName` VARCHAR(300) NULL AFTER `DeliveryTime`,
ADD COLUMN `ProductLine` VARCHAR(100) NULL AFTER `PartName`,
ADD COLUMN `CategoryId` INT(10) NULL AFTER `ProductLine`,
ADD COLUMN `SubCategoryId` INT(10) NULL AFTER `CategoryId`,
ADD COLUMN `Unit` VARCHAR(20) NULL AFTER `SubCategoryId`,
ADD COLUMN `FeatureAndBenefits` TEXT(65535) NULL AFTER `Unit`,
ADD COLUMN `FeatureAndBenefitsUrl` TEXT(2000) NULL AFTER `FeatureAndBenefits`,
ADD COLUMN `FeatureAndBenefitsUrlText` TEXT(65535) NULL AFTER `FeatureAndBenefitsUrl`,
ADD COLUMN `Warranty` TEXT(65535) NULL AFTER `FeatureAndBenefitsUrlText`,
ADD COLUMN `WarrantyUrl` TEXT(2000) NULL AFTER `Warranty`,
ADD COLUMN `Msds` TEXT(65535) NULL AFTER `WarrantyUrl`,
ADD COLUMN `MsdsUrl` TEXT(2000) NULL AFTER `Msds`,
ADD COLUMN `DetailUrl` TEXT(2000) NULL AFTER `MsdsUrl`,
ADD COLUMN `Manufacturer` VARCHAR(200) NULL AFTER `DetailUrl`,
ADD COLUMN `ManufacturerPartNumber` VARCHAR(50) NULL AFTER `Manufacturer`,
ADD COLUMN `UNSPSC` VARCHAR(50) NULL AFTER `ManufacturerPartNumber`;


ALTER TABLE `dotnet`.`parts` 
CHANGE COLUMN `PartName` `PartName` VARCHAR(300) NULL DEFAULT NULL AFTER `PartNumber`,
CHANGE COLUMN `ProductLine` `ProductLine` VARCHAR(100) NULL DEFAULT NULL AFTER `PartName`,
CHANGE COLUMN `CategoryId` `CategoryId` INT(10) NULL DEFAULT NULL AFTER `Category`,
CHANGE COLUMN `SubCategoryId` `SubCategoryId` VARCHAR(40) NULL DEFAULT NULL AFTER `SubCategory`,
CHANGE COLUMN `Unit` `Unit` VARCHAR(20) NULL DEFAULT NULL AFTER `Core`,
CHANGE COLUMN `QuantityPricingUpdatedDate` `QuantityPricingUpdatedDate` DATETIME NULL DEFAULT '2001-01-01 00:00:00' AFTER `DeliveryTime`,
CHANGE COLUMN `ObjectData` `ObjectData` JSON NOT NULL AFTER `UNSPSC`;

ALTER TABLE `dotnet`.`parts` 
CHANGE COLUMN `SubCategoryId` `SubCategoryId` VARCHAR(40) NULL DEFAULT NULL ;


ALTER TABLE `dotnet`.`parts` 
CHARACTER SET = utf8mb4 ,
CHANGE COLUMN `PartNumber` `PartNumber` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL ,
CHANGE COLUMN `PartName` `PartName` VARCHAR(300) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `ProductLine` `ProductLine` VARCHAR(100) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `Category` `Category` VARCHAR(200) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `SubCategory` `SubCategory` VARCHAR(200) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `SubCategoryId` `SubCategoryId` VARCHAR(40) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `Unit` `Unit` VARCHAR(20) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `DCName` `DCName` VARCHAR(200) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `DeliveryTime` `DeliveryTime` VARCHAR(200) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `FeatureAndBenefits` `FeatureAndBenefits` TEXT CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `FeatureAndBenefitsUrl` `FeatureAndBenefitsUrl` TEXT CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `FeatureAndBenefitsUrlText` `FeatureAndBenefitsUrlText` TEXT CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `Warranty` `Warranty` TEXT CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `WarrantyUrl` `WarrantyUrl` TEXT CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `Msds` `Msds` TEXT CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `MsdsUrl` `MsdsUrl` TEXT CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `DetailUrl` `DetailUrl` TEXT CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `Manufacturer` `Manufacturer` VARCHAR(200) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `ManufacturerPartNumber` `ManufacturerPartNumber` VARCHAR(50) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `UNSPSC` `UNSPSC` VARCHAR(50) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ;

ALTER TABLE `dotnet`.`partcompatibility` 
CHARACTER SET = utf8mb4 ,
CHANGE COLUMN `CompatibilityKey` `CompatibilityKey` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL ,
CHANGE COLUMN `PartNumber` `PartNumber` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL ,
CHANGE COLUMN `Make` `Make` VARCHAR(200) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `Model` `Model` VARCHAR(200) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ,
CHANGE COLUMN `Engine` `Engine` VARCHAR(1000) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL ;



