//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCPDotNetOrderInventory {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Invoices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Invoices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCPDotNetOrderInventory.Invoices", typeof(Invoices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;InvoiceDetailResponse StatusCode=&quot;0&quot;&gt;
        ///  &lt;StoreID&gt;600006011&lt;/StoreID&gt;
        ///  &lt;TransactionType&gt;CHG&lt;/TransactionType&gt;
        ///  &lt;InvoiceNumber&gt;398176&lt;/InvoiceNumber&gt;
        ///  &lt;InvoiceTotal&gt;44.10&lt;/InvoiceTotal&gt;
        ///  &lt;InvoiceDate&gt;050420&lt;/InvoiceDate&gt;
        ///  &lt;InvoiceTime&gt;1739&lt;/InvoiceTime&gt;
        ///  &lt;CounterPersonID&gt;6&lt;/CounterPersonID&gt;
        ///  &lt;SalesPersonID&gt;17&lt;/SalesPersonID&gt;
        ///  &lt;OtherCharges&gt;0.00&lt;/OtherCharges&gt;
        ///  &lt;NonTaxableTotal&gt;44.10&lt;/NonTaxableTotal&gt;
        ///  &lt;TaxableTotal&gt;0.00&lt;/TaxableTotal&gt;
        ///  &lt;Tax1Total&gt;0.00&lt;/Tax1Total&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
    }
}
